name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Install PM2
      run: npm install pm2 -g

    - name: Connect to Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey=${{ secrets.TS_AUTHKEY }} --accept-routes=false --accept-dns=false
        tailscale status

    - name: Deploy to RP5
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 10m
        script: |
          cd /home/randan/projects/ua-taxes-tg-bot
          git pull origin master
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm ci
          npm run build
          pm2 restart ua-taxes-tg-bot 2>/dev/null || pm2 start npm --name "ua-taxes-tg-bot" -- start
          pm2 save